ktor:
  application:
    modules:
      - cloud.mallne.dicentra.areaassist.synapse.ApplicationKt.module
  deployment:
    port: 8080

server:
  hostname: "$CORS_ALL:"
  cors:
    all: "$CORS_ALL:false"
    hosts: "$CORS_HOSTS:"

data:
  url: "$DATA_URL"
  user: "$DATA_USER"
  password: "$DATA_PASSWORD"
  schema: "$DATA_SCHEMA:areaassist_synapse"

catalyst:
  enabled: "$CATALYST_ENABLED:true"
  anonymous: "$CATALYST_ANONYMOUS:true"
  aggregation:
    enabled: "$CATALYST_AGGREGATION_ENABLED:true"
    anonymous: "$CATALYST_AGGREGATION_ANONYMOUS:true"

security:
  enabled: "$SECURITY_ENABLED:false"
  issuer: "$SECURITY_ISSUER:"
  scopes: "$SECURITY_SCOPES:"
  client_id: "$SECURITY_CLIENTID:"
  client_secret: "$SECURITY_CLIENTSECRET:"
  role_scope: "$SECURITY_ROLESCOPE:"
  app:
    issuer: "$SECURITY_ISSUER:"
    scopes: "$SECURITY_APP_SCOPES:"
    client_id: "$SECURITY_APP_CLIENTID:"
  roles:
    user: "$SECURITY_ROLES_USER:"
    admin: "$SECURITY_ROLES_ADMIN:"
    superadmin: "$SECURITY_ROLES_SUPERADMIN:"