ktor:
  application:
    modules:
      - cloud.mallne.dicentra.areaassist.codex.ApplicationKt.codexModule
  deployment:
    port: 8080

server:
  tls_enabled: "$TLSENABLED:true"
  hostname: "$HOSTNAME:"
  info: "$INFO:DiCentra AreaAssist Codex"
  description: "$DESCRIPTION:A discovery for AreaAssist."
  base_locator: "DCAACodex"
  discovery_exclusions: "$DISCOVERY_EXCLUSIONS:"
  cors:
    all: "$CORS_ALL:false"
    hosts: "$CORS_HOSTS:"

data:
  url: "$DATA_URL"
  user: "$DATA_USER"
  password: "$DATA_PASSWORD"
  schema: "$DATA_SCHEMA:codex"
  migrations:
    - "db/migration"
  callbacks:
    - "db/callback"
  auto_create_delta: "$DATA_AUTOCREATEDELTA:false"
  migration_name: "$DATA_MIGRATIONNAME:V0__create.generated"

catalyst:
  enabled: "$CATALYST_ENABLED:true"
  anonymous: "$CATALYST_ANONYMOUS:true"
  server_name: "$CATALYST_SERVERNAME:"
  tls_enabled: "$CATALYST_TLSENABLED:true"
  title: "$CATALYST_TITLE:Synapse Catalyst"
  description: "$CATALYST_DESCRIPTION:Make Requests to a stored Service in a single Tenant setup."

preferred_transform: "$PREFERRED_TRANSFORM:Native"

security:
  enabled: "$SECURITY_ENABLED:false"
  issuer: "$SECURITY_ISSUER:"
  scopes: "$SECURITY_SCOPES:"
  client_id: "$SECURITY_CLIENTID:"
  client_secret: "$SECURITY_CLIENTSECRET:"
  areaassist_client_id: "$SECURITY_AREAASSIST_CLIENTID:"
  areaassist_client_name: "$SECURITY_AREAASSIST_CLIENTNAME:"
  areaassist_account_console: "$SECURITY_AREAASSIST_ACCOUNTCONSOLE:"
  groups:
    user: "$SECURITY_GROUPS_USER:"
    admin: "$SECURITY_GROUPS_ADMIN:"
    superadmin: "$SECURITY_GROUPS_SUPERADMIN:"